#!/usr/bin/env python

from iron_worker import *
import time

current_milli_time = lambda: int(round(time.time() * 1000))

worker = IronWorker()
task = Task(code_name="pushSceneToChannel")
task.payload = {
"payload":
'http://loqootv.com/log?eventType=pushSceneToChannel&networkName="ocdmusicii"&networkEmail="ron@loqoo.tv"&channelName="loqootv"&sceneType="originalAudio"&sceneUrl="https://s3-us-west-1.amazonaws.com/loqootvstar/loqootv_178fd92a92f014284d3a5f12a36fca8c.mp3"&sceneDescp="uhhuh"&sceneTag1="ok"&sceneTag3="ko"&sceneTip="22"&sceneTipDnom="BTC"&networkAvatar=&timestamp=current_milli_time();'
}
response = worker.queue(task)


